config/routes.rb
Sudoku31::Application.routes.draw do
  resources :puzzles do
  	resources :sudokus
  end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/models/puzzle.rb
class Puzzle
  include Mongoid::Document
  cattr_reader :per_page
  @@per_page = 5
  field :level, :type => Integer
  field :name, :type => String
  field :cellstring, :type => String
  field :description, :type => String
  field :createon, :type => Time, :default => Time.now
  field :createby, :type => String
  
  embeds_many :sudokus
  
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :level
  validates_presence_of :cellstring
  validates_inclusion_of :level, :in => 1..4
  
  validate :validate_sudoku?
  
  def validate_sudoku? 
  	#numericality
    1.upto(9) do |x|
      1.upto(9) do |y|
        #if cellxy found, should be cellxy:[1-9]
        pattrn = Regexp.new("cell"+x.to_s+y.to_s+":")
        if self.cellstring.match(pattrn)
        #ruby's string.scan doesn't return nil even no match
          pattrn = Regexp.new("(cell"+x.to_s+y.to_s+":(.|$)(?=,|$))")
          matchedCellArray = self.cellstring.scan(pattrn)
          #scan will return an empty array if no match
          next if matchedCellArray.length == 0
          errors.add(:cellstring, "one cell assigned value once") if matchedCellArray.length != 1
          tmpString = matchedCellArray[0][0]
          #ruby's scan is very different from javascript global match!!!
          tmpLen = tmpString.length
          next if tmpLen == 7 || (tmpLen == 8 && tmpString[7] == ',')
          tmpScope = '1'..'9'
          errors.add(:cellstring, "only 1..9 allowed") if (tmpLen == 8 && !tmpScope.include?(tmpString[7])) 
        end
      end
    end
    
    #row by row
    1.upto(9) do |v|
	  1.upto(9) do |x|
        pattrn = Regexp.new("cell"+x.to_s+"[1-9]{1}:"+v.to_s)
        v_times = self.cellstring.scan(pattrn).length
        errors.add(:cellstring, "1..9 only appear once in one line") if (v_times > 0 && v_times != 1)
      end
    end
    
    #col by col
    1.upto(9) do |v|
      1.upto(9) do |y|
        pattrn = Regexp.new("cell"+"[1-9]{1}"+y.to_s+":"+v.to_s)
        v_times = self.cellstring.scan(pattrn).length
        errors.add(:cellstring, "1..9 only appear once in one row") if (v_times > 0 && v_times != 1)
      end
    end
    
    #small grid by grid
    1.upto(9) do |v|
      #grid 11-12-13-21-22-23-31-32-33
      pattrn = Regexp.new("cell"+"(11|12|13|21|22|23|31|32|33)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 14-...-36
      pattrn = Regexp.new("cell"+"(14|15|16|24|25|26|34|35|36)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 17-...-39
      pattrn = Regexp.new("cell"+"(17|18|19|27|28|29|37|38|39)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      
      #grid 41-42-43-51-52-53-61-62-63
      pattrn = Regexp.new("cell"+"(41|42|43|51|52|53|61|62|63)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 44-...-66
      pattrn = Regexp.new("cell"+"(44|45|46|54|55|56|64|65|66)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 47-...-69
      pattrn = Regexp.new("cell"+"(47|48|49|57|58|59|67|68|69)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      
      #grid 71-72-73-81-82-83-91-92-93
      pattrn = Regexp.new("cell"+"(71|72|73|81|82|83|91|92|93)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 74-...-96
      pattrn = Regexp.new("cell"+"(74|75|76|84|85|86|94|95|96)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
      #grid 77-...-99
      pattrn = Regexp.new("cell"+"(77|78|79|87|88|89|97|98|99)"+":"+v.to_s)
      v_times = self.cellstring.scan(pattrn).length
      errors.add(:cellstring, "1..9 only appear once in one grid") if (v_times > 0 && v_times != 1)
    end
  	
  	return true
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /puzzles
  # GET /puzzles.json
  def index
    puzzles_all = Puzzle.all
    @puzzles = puzzles_all.paginate :page => params[:page],:per_page => 5
    @puzzleOnShow = getPuzzleOnShow(@puzzles.first)
    @gridOption = "playable"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @puzzles }
    end
  end

  # GET /puzzles/1
  # GET /puzzles/1.json
  def show
    @puzzle = Puzzle.find(params[:id])
    @puzzleOnShow = getPuzzleOnShow(@puzzle)
    @gridOption = "playable"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @puzzle }
    end
  end

  # GET /puzzles/new
  # GET /puzzles/new.json
  def new
    @puzzle = Puzzle.new
    @puzzleOnShow = getPuzzleOnShow(@puzzle)
    @gridOption = "editable"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @puzzle }
    end
  end

  # GET /puzzles/1/edit
  def edit
    @puzzle = Puzzle.find(params[:id])
    @puzzleOnShow = getPuzzleOnShow(@puzzle)
    @gridOption = "editable"
  end

  # POST /puzzles
  # POST /puzzles.json
  def create
    @puzzle = Puzzle.new(params[:puzzle])
    @puzzleOnShow = getPuzzleOnShow(@puzzle)
    @gridOption = "editable"

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render json: @puzzle, status: :created, location: @puzzle }
      else
        format.html { render action: "new" }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /puzzles/1
  # PUT /puzzles/1.json
  def update
    @puzzle = Puzzle.find(params[:id])
    @puzzleOnShow = getPuzzleOnShow(@puzzle)
    @gridOption = "editable"

    respond_to do |format|
      if @puzzle.update_attributes(params[:puzzle])
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzles/1
  # DELETE /puzzles/1.json
  def destroy
    @puzzle = Puzzle.find(params[:id])
    @puzzle.destroy

    respond_to do |format|
      format.html { redirect_to puzzles_url }
      format.json { head :ok }
    end
  end
  
  def getPuzzleOnShow(puzzle)
  	if !puzzle
  		return "cell11:6cell31:8cell22:7cell23:1cell24:6cell25:2cell14:3cell17:1cell36:1cell33:5cell41:5cell61:4cell53:9cell63:7cell44:8cell45:7cell65:6cell66:9cell47:9cell57:6cell49:1cell69:8cell74:2cell77:8cell79:7cell87:4cell88:1cell99:2cell85:8cell86:6cell96:3cell93:8"
  	end
  	puzzle.cellstring
  end
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/puzzles/_form.html.haml
#puzzle_form_convas
  = form_for @puzzle do |f|
    -if @puzzle.errors.any?
      #error_explanation
        %h2= "#{pluralize(@puzzle.errors.count, "error")} prohibited this puzzle from being saved:"
        %ul
          - @puzzle.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :level
      <br/>
      = f.select :level, [["easy *", 1], ["normal **",2], ["difficult ***",3], ["extreme ****",4]]
    .field
      = f.label :name
      <br/>
      = f.text_field :name, :size => 25, :maxlength => 25
    .field
      = f.hidden_field :createon
    .field
      = f.hidden_field :cellstring
    .field
      = f.label :description
      <br/>
      = f.text_area :description, :size => "20x5", :maxlength => 50
    .actions
      = f.submit 'Save'

= render 'hidden_options'

app/views/puzzles/_hidden_options.html.haml
.hiddenOptions
  %ul#puzzleOnShow
    = @puzzleOnShow
  %ul#gridOption
    = @gridOption

app/views/puzzles/edit.html.haml
%h3 Editing puzzle

= render 'form'

= link_to 'Back', puzzles_path

app/views/puzzles/index.html.haml
#puzzles_list_convas
  %table#puzzles_list
    %tr
      %th Level
      %th Name
      %th.Description Description
      %th.ActionEdit
      %th.ActionDestroy

    - @puzzles.each do |puzzle|
      %tr
        %td= puzzle.level
        %td= puzzle.name
        %td= puzzle.description
        %td.hiddenField= puzzle.cellstring
        %td= link_to 'Edit', edit_puzzle_path(puzzle)
        %td= link_to 'Delete', puzzle, :confirm => 'Are you sure?', :method => :delete
    
  = will_paginate @puzzles
  
  = link_to 'New Puzzle', new_puzzle_path

%br

= render 'hidden_options'

app/views/puzzles/new.html.haml
%h2 New puzzle

= render 'form'

= link_to 'Back', puzzles_path

app/views/puzzles/show.html.haml
%p#notice= notice

#puzzles_list_convas
  %table#puzzles_list
    %tr
      %th Level
      %th Name
      %th.Description Description
      %th.ActionEdit
      %th.ActionDestroy

    %tr
      %td= @puzzle.level
      %td= @puzzle.name
      %td= @puzzle.description
      %td.hiddenField= @puzzle.cellstring
      %td= link_to 'Edit', edit_puzzle_path(@puzzle)
      %td= link_to 'Delete', @puzzle, :confirm => 'Are you sure?', :method => :delete

= render 'hidden_options'